### ISSUE TITLE
rx580 not found

### ISSUE THREAD

**Issue by Quake4** [jceminer/cn_gpu_miner#24]
```
              +-------------------------------------------+
              | JC Expert Cryptonote CPU+GPU Miner 0.33b2 |
              +-------------------------------------------+


For Windows 64-bits
Analyzing Processors topology...
Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
Assembly codename: generic_aes_avx
  SSE2    : Yes
  SSE3    : Yes
  SSE4    : Yes
  AES     : Yes
  AVX     : Yes
  AVX2    : No

Found CPU 0, with:
  L1 Cache:    32 KB
  L2 Cache:   256 KB
  L3 Cache:  6144 KB, shared with CPU 1, 2, 3
Found CPU 1, with:
  L1 Cache:    32 KB
  L2 Cache:   256 KB
  L3 Cache:  6144 KB, shared with CPU 0, 2, 3
Found CPU 2, with:
  L1 Cache:    32 KB
  L2 Cache:   256 KB
  L3 Cache:  6144 KB, shared with CPU 0, 1, 3
Found CPU 3, with:
  L1 Cache:    32 KB
  L2 Cache:   256 KB
  L3 Cache:  6144 KB, shared with CPU 0, 1, 2

Detecting OpenCL-capable GPUs...
CL_UNKNOWN_ERROR -1001
```

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/47633541-5937b800-db5f-11e8-9190-41a3c19ffd05.png)

**Comment by jceminer** [comment]
Are you running Windows 7?
If yes, so Win7 is just not supported, Win8.1 and later are.

**Comment by Quake4** [comment]
yes. win7. why win7 isnt supported?

**Comment by jceminer** [comment]
Because my OpenCL code is not _compiled_ like with xmrstak, but somehow _injected_ into the drivers, to prevent hacking involving stubbing the OpenCL api (a simple hack everybody can do). But that technique doesn't work on Win7, and i could find a way to keep both security and compatibility so I dropped Win7 support for GPU (CPU mining is ok down to Vista32).
Go to the Bitcointalk topic for the full story.

**Comment by Quake4** [comment]
Thanks
